### ISSUE TITLE
Pressing Ctrl+r doesn't do anything

### ISSUE THREAD

**Issue by maxigaz** [guidocella/mpv-lua-repl#1]
I downloaded and moved `lua-repl.lua` into `~/.config/mpv/scripts`. There's no reaction in mpv's main window or in any of its terminal output when I press Ctrl+r.

I've also tried a different key combination by pasting `Ctrl+e script-binding lua-repl` into `~/.config/mpv/input.conf` (after making sure Ctrl+e is not bound to anything), and I had the same results.

This is with mpv v0.37.0 under Arch Linux.

**Comment by guidocella** [comment]
You currently need git master to use mp.input.

**Comment by maxigaz** [comment]
> You currently need git master to use mp.input.

Oh, by that, you meant the master branch of *mpv*? I didn't think of that. Thank you for clarifying it!

**Comment by guidocella** [comment]
Yeah, I added it to the README to make it clear.
